// This file will be auto-generated by Supabase CLI
// For now, we define a basic structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      modules: {
        Row: {
          id: string
          title: string
          description: string
          difficulty: 'beginner' | 'intermediate' | 'advanced'
          category: string
          content: Json
          order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          difficulty: 'beginner' | 'intermediate' | 'advanced'
          category: string
          content: Json
          order: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          difficulty?: 'beginner' | 'intermediate' | 'advanced'
          category?: string
          content?: Json
          order?: number
          created_at?: string
          updated_at?: string
        }
      }
      user_progress: {
        Row: {
          id: string
          user_id: string
          module_id: string
          completed: boolean
          progress_percentage: number
          last_accessed: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          module_id: string
          completed?: boolean
          progress_percentage?: number
          last_accessed?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          module_id?: string
          completed?: boolean
          progress_percentage?: number
          last_accessed?: string
          created_at?: string
          updated_at?: string
        }
      }
      quizzes: {
        Row: {
          id: string
          module_id: string
          title: string
          questions: Json
          passing_score: number
          created_at: string
        }
        Insert: {
          id?: string
          module_id: string
          title: string
          questions: Json
          passing_score?: number
          created_at?: string
        }
        Update: {
          id?: string
          module_id?: string
          title?: string
          questions?: Json
          passing_score?: number
          created_at?: string
        }
      }
      quiz_attempts: {
        Row: {
          id: string
          user_id: string
          quiz_id: string
          score: number
          answers: Json
          passed: boolean
          completed_at: string
        }
        Insert: {
          id?: string
          user_id: string
          quiz_id: string
          score: number
          answers: Json
          passed: boolean
          completed_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          quiz_id?: string
          score?: number
          answers?: Json
          passed?: boolean
          completed_at?: string
        }
      }
      companies: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string | null
          description: string | null
          focus_areas: string[]
          difficulty_level: 'easy' | 'medium' | 'hard'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          logo_url?: string | null
          description?: string | null
          focus_areas?: string[]
          difficulty_level?: 'easy' | 'medium' | 'hard'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          logo_url?: string | null
          description?: string | null
          focus_areas?: string[]
          difficulty_level?: 'easy' | 'medium' | 'hard'
          created_at?: string
          updated_at?: string
        }
      }
      interview_questions: {
        Row: {
          id: string
          company_id: string
          type: 'system_design' | 'coding' | 'behavioral'
          difficulty: 'easy' | 'medium' | 'hard'
          title: string
          content: string
          hints: string[] | null
          sample_answer: Json | null
          topics: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          company_id: string
          type: 'system_design' | 'coding' | 'behavioral'
          difficulty: 'easy' | 'medium' | 'hard'
          title: string
          content: string
          hints?: string[] | null
          sample_answer?: Json | null
          topics?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          company_id?: string
          type?: 'system_design' | 'coding' | 'behavioral'
          difficulty?: 'easy' | 'medium' | 'hard'
          title?: string
          content?: string
          hints?: string[] | null
          sample_answer?: Json | null
          topics?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      study_plans: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          target_company_id: string | null
          duration_weeks: number
          questions_per_day: number
          status: 'active' | 'completed' | 'paused'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string
          name: string
          description?: string | null
          target_company_id?: string | null
          duration_weeks?: number
          questions_per_day?: number
          status?: 'active' | 'completed' | 'paused'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          target_company_id?: string | null
          duration_weeks?: number
          questions_per_day?: number
          status?: 'active' | 'completed' | 'paused'
          created_at?: string
          updated_at?: string
        }
      }
      study_plan_items: {
        Row: {
          id: string
          plan_id: string
          question_id: string
          day_number: number
          status: 'pending' | 'completed' | 'skipped'
          completed_at: string | null
          user_notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          plan_id: string
          question_id: string
          day_number: number
          status?: 'pending' | 'completed' | 'skipped'
          completed_at?: string | null
          user_notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          plan_id?: string
          question_id?: string
          day_number?: number
          status?: 'pending' | 'completed' | 'skipped'
          completed_at?: string | null
          user_notes?: string | null
          created_at?: string
        }
      }
      question_attempts: {
        Row: {
          id: string
          user_id: string
          question_id: string
          attempt_number: number
          user_answer: string | null
          time_spent_seconds: number | null
          was_correct: boolean | null
          feedback: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          question_id: string
          attempt_number?: number
          user_answer?: string | null
          time_spent_seconds?: number | null
          was_correct?: boolean | null
          feedback?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          question_id?: string
          attempt_number?: number
          user_answer?: string | null
          time_spent_seconds?: number | null
          was_correct?: boolean | null
          feedback?: Json | null
          created_at?: string
        }
      }
      interview_sessions: {
        Row: {
          id: string
          user_id: string
          company_id: string | null
          interview_type: 'system_design' | 'coding' | 'behavioral'
          difficulty: 'easy' | 'medium' | 'hard'
          status: 'pending' | 'in_progress' | 'completed' | 'cancelled'
          questions_asked: Json
          user_responses: Json
          feedback: Json | null
          score: number | null
          duration_seconds: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string
          company_id?: string | null
          interview_type: 'system_design' | 'coding' | 'behavioral'
          difficulty?: 'easy' | 'medium' | 'hard'
          status?: 'pending' | 'in_progress' | 'completed' | 'cancelled'
          questions_asked?: Json
          user_responses?: Json
          feedback?: Json | null
          score?: number | null
          duration_seconds?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          company_id?: string | null
          interview_type?: 'system_design' | 'coding' | 'behavioral'
          difficulty?: 'easy' | 'medium' | 'hard'
          status?: 'pending' | 'in_progress' | 'completed' | 'cancelled'
          questions_asked?: Json
          user_responses?: Json
          feedback?: Json | null
          score?: number | null
          duration_seconds?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      interview_transcripts: {
        Row: {
          id: string
          session_id: string
          question: string
          response: string | null
          follow_up_questions: Json
          feedback: string | null
          score: number | null
          timestamp: string
        }
        Insert: {
          id?: string
          session_id: string
          question: string
          response?: string | null
          follow_up_questions?: Json
          feedback?: string | null
          score?: number | null
          timestamp?: string
        }
        Update: {
          id?: string
          session_id?: string
          question?: string
          response?: string | null
          follow_up_questions?: Json
          feedback?: string | null
          score?: number | null
          timestamp?: string
        }
      }
      chat_messages: {
        Row: {
          id: string
          user_id: string
          role: 'user' | 'assistant'
          content: string
          context: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string
          role: 'user' | 'assistant'
          content: string
          context?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          role?: 'user' | 'assistant'
          content?: string
          context?: Json | null
          created_at?: string
        }
      }
      achievements: {
        Row: {
          id: string
          name: string
          description: string
          icon: string
          category: 'learning' | 'streak' | 'quiz' | 'interview' | 'design' | 'community'
          criteria: Json
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description: string
          icon: string
          category: 'learning' | 'streak' | 'quiz' | 'interview' | 'design' | 'community'
          criteria: Json
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string
          icon?: string
          category?: 'learning' | 'streak' | 'quiz' | 'interview' | 'design' | 'community'
          criteria?: Json
          created_at?: string
        }
      }
      user_achievements: {
        Row: {
          id: string
          user_id: string
          achievement_id: string
          unlocked_at: string
        }
        Insert: {
          id?: string
          user_id: string
          achievement_id: string
          unlocked_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          achievement_id?: string
          unlocked_at?: string
        }
      }
      learning_paths: {
        Row: {
          id: string
          name: string
          description: string
          role: 'backend' | 'frontend' | 'fullstack' | 'devops' | 'sre'
          level: 'junior' | 'mid' | 'senior' | 'staff' | 'principal'
          module_ids: string[]
          estimated_hours: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description: string
          role: 'backend' | 'frontend' | 'fullstack' | 'devops' | 'sre'
          level: 'junior' | 'mid' | 'senior' | 'staff' | 'principal'
          module_ids?: string[]
          estimated_hours?: number
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string
          role?: 'backend' | 'frontend' | 'fullstack' | 'devops' | 'sre'
          level?: 'junior' | 'mid' | 'senior' | 'staff' | 'principal'
          module_ids?: string[]
          estimated_hours?: number
          created_at?: string
        }
      }
      user_learning_paths: {
        Row: {
          id: string
          user_id: string
          path_id: string
          status: 'active' | 'completed' | 'paused'
          started_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          path_id: string
          status?: 'active' | 'completed' | 'paused'
          started_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          path_id?: string
          status?: 'active' | 'completed' | 'paused'
          started_at?: string
          completed_at?: string | null
        }
      }
      content_embeddings: {
        Row: {
          id: string
          content: string
          embedding: number[]
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          content: string
          embedding: number[]
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          content?: string
          embedding?: number[]
          metadata?: Json
          created_at?: string
        }
      }
      shared_designs: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          design_data: Json
          preview_image: string | null
          difficulty: 'easy' | 'medium' | 'hard'
          tags: string[]
          likes_count: number
          comments_count: number
          views_count: number
          is_featured: boolean
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          design_data: Json
          preview_image?: string | null
          difficulty?: 'easy' | 'medium' | 'hard'
          tags?: string[]
          likes_count?: number
          comments_count?: number
          views_count?: number
          is_featured?: boolean
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string | null
          design_data?: Json
          preview_image?: string | null
          difficulty?: 'easy' | 'medium' | 'hard'
          tags?: string[]
          likes_count?: number
          comments_count?: number
          views_count?: number
          is_featured?: boolean
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      design_comments: {
        Row: {
          id: string
          design_id: string
          user_id: string
          content: string
          parent_id: string | null
          likes_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          design_id: string
          user_id: string
          content: string
          parent_id?: string | null
          likes_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          design_id?: string
          user_id?: string
          content?: string
          parent_id?: string | null
          likes_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      discussions: {
        Row: {
          id: string
          user_id: string
          title: string
          content: string
          category: string
          tags: string[]
          replies_count: number
          views_count: number
          is_pinned: boolean
          is_hot: boolean
          last_reply_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          content: string
          category: string
          tags?: string[]
          replies_count?: number
          views_count?: number
          is_pinned?: boolean
          is_hot?: boolean
          last_reply_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          content?: string
          category?: string
          tags?: string[]
          replies_count?: number
          views_count?: number
          is_pinned?: boolean
          is_hot?: boolean
          last_reply_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      discussion_replies: {
        Row: {
          id: string
          discussion_id: string
          user_id: string
          parent_id: string | null
          content: string
          likes_count: number
          is_accepted_answer: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          discussion_id: string
          user_id: string
          parent_id?: string | null
          content: string
          likes_count?: number
          is_accepted_answer?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          discussion_id?: string
          user_id?: string
          parent_id?: string | null
          content?: string
          likes_count?: number
          is_accepted_answer?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      likes: {
        Row: {
          id: string
          user_id: string
          likeable_type: 'design' | 'discussion' | 'reply' | 'comment'
          likeable_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          likeable_type: 'design' | 'discussion' | 'reply' | 'comment'
          likeable_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          likeable_type?: 'design' | 'discussion' | 'reply' | 'comment'
          likeable_id?: string
          created_at?: string
        }
      }
      user_scores: {
        Row: {
          id: string
          user_id: string
          score: number
          streak: number
          last_activity_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          score?: number
          streak?: number
          last_activity_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          score?: number
          streak?: number
          last_activity_date?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      user_badges: {
        Row: {
          id: string
          user_id: string
          badge_id: string
          earned_at: string
        }
        Insert: {
          id?: string
          user_id: string
          badge_id: string
          earned_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          badge_id?: string
          earned_at?: string
        }
      }
      badges: {
        Row: {
          id: string
          name: string
          description: string
          icon: string
          category: string
          criteria: Json
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description: string
          icon: string
          category: string
          criteria: Json
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string
          icon?: string
          category?: string
          criteria?: Json
          created_at?: string
        }
      }
      collaboration_sessions: {
        Row: {
          id: string
          design_id: string
          owner_id: string
          status: 'active' | 'ended'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          design_id: string
          owner_id: string
          status?: 'active' | 'ended'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          design_id?: string
          owner_id?: string
          status?: 'active' | 'ended'
          created_at?: string
          updated_at?: string
        }
      }
      collaboration_participants: {
        Row: {
          id: string
          session_id: string
          user_id: string
          user_name: string
          user_color: string
          is_active: boolean
          cursor_position: Json | null
          selected_nodes: Json | null
          joined_at: string
          last_seen_at: string
        }
        Insert: {
          id?: string
          session_id: string
          user_id: string
          user_name: string
          user_color: string
          is_active?: boolean
          cursor_position?: Json | null
          selected_nodes?: Json | null
          joined_at?: string
          last_seen_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          user_id?: string
          user_name?: string
          user_color?: string
          is_active?: boolean
          cursor_position?: Json | null
          selected_nodes?: Json | null
          joined_at?: string
          last_seen_at?: string
        }
      }
      knowledge_mastery: {
        Row: {
          id: string
          user_id: string
          path_id: string
          node_id: string
          mastery_score: number
          time_spent_minutes: number
          last_activity_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          path_id: string
          node_id: string
          mastery_score?: number
          time_spent_minutes?: number
          last_activity_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          path_id?: string
          node_id?: string
          mastery_score?: number
          time_spent_minutes?: number
          last_activity_at?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
